services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      PYTHONUNBUFFERED: ${BUFFER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - 8000:8000 
    volumes:
      - ./backend:/usr/local/app
      - /usr/local/app/.venv
      - media_data:/usr/local/app/media
    depends_on:
      - db

volumes:
  postgres_data:
  media_data:
