version: "3.9"

services:
  db:
    build:
      context: ./db
    env_file:
      - .env.sample
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
